appsignal/diagnose_tests

spec/diagnose_spec.rb

Depends on #1
Build fails because the Semaphore setup is only added in #2 
Remove the difference between the Node.js and Ruby integrations,
printing a different number of lines. This has been fixed in the Node.js
integration.
The log file should always end with an empty line. When it does not, the
logger will write the next line at the end of the last logged line.
```
line 1line 2
```
But because the logger will always end the log line with a line break,
our dummy log should too. The next time the logger will log a line it
will look like this instead:
```
line 1
line 2
```
This will help debug the assertion failure, as you can see the full
output that was asserted again. If one line fails, the assertion failure
message can be something like `\n` didn't match `<complex regex>`.
Without the …

Nodejs log lines

---

spec/diagnose_spec.rb

Reapply of #3 because I merged it in the wrong branch.
[skip review]
Remove the difference between the Node.js and Ruby integrations,
printing a different number of lines. This has been fixed in the Node.js
integration.
The log file should always end with an empty line. When it does not, the
logger will write the next line at the end of the last logged line.
```
line 1line 2
```
But because the logger will always end the log line with a line break,
our dummy log should too. The next time the logger will log a line it
will look like this instead:
```
line 1
line 2
```
This will help debug the assertion failure, as you can see the full
output that was asserted again. If one line fails, the assertion failure
message can be something like `\n` didn't match `<complex regex>`.
Without the …

Nodejs log lines2

---

spec/diagnose_spec.rb

This has been implemented in the Node.js integration diagnose report so
it doesn't always return "valid".

Remove exception for Node.js key validation

---

.gitignore
.rubocop.yml
.semaphore/semaphore.yml
Gemfile
Gemfile.lock
ruby/Gemfile
spec/diagnose_spec.rb

Do not rely on the appsignal-ruby RuboCop, but instead add our own. This
way we can also use a more recent RuboCop version.
I also fixed any issues that arose. Some parts automatically corrected
by RuboCop, some required a manual touch.

Add RuboCop linting to project

---

spec/diagnose_spec.rb

The Node.js integration's install report is now stored with a more
unique filename based on the app install path. This way it doesn't
overwrite the install report if multiple apps on the same host use the
AppSignal package.
appsignal/appsignal-nodejs#412
The diagnose tests wrote the install report to an outdated location and
thus wasn't actually used by the diagnose tests. This came to light when
changing the install script of the Node.js integration to always write
an install report, also for local installs. This change has not been
merged at time of writing, but highlighted this issue that is a problem
now. Previously it worked accidentally because the installer wrote a new
report upon installation and that happened to match the expected ouput.
Adapt the new naming scheme as introduced …

Fix the Node.js install report location

---

spec/diagnose_spec.rb
spec/spec_helper.rb
spec/support/runner.rb
spec/support/runner_helper.rb

Based on #13 
Required for https://github.com/appsignal/appsignal-nodejs/pull/454
Don't fetch and initialize the runner instance in every test itself, but
add a helper for it with additional error handling.
I removed the "ruby" default, because it burned me a couple times when I
hadn't set the LANGUAGE environment variable. It's better to just have
it error when that happens and have all integrations behave the same.
When no agent and extension install report is present on the file
system, test if the diagnose command prints the error correctly.
To communicate to the runner that the install report should be created I
added an options argument to the Runner class, which can be expanded
with other future options.

Test missing install report

---

Gemfile
Gemfile.lock
spec/diagnose_spec.rb
spec/spec_helper.rb
spec/support/diagnose_report_helper.rb
spec/support/output_helper.rb
spec/support/server.rb

Part of https://github.com/appsignal/integration-guide/issues/59
---
Rename the expect_section to expect_output_for. This name is more clear,
it asserts the output of the runner, for a specific section.
To test the diagnose reports for all integrations, submit the reports
from the integrations to a mock server for the test suite.
This mock server will receive the report and parse the JSON. Then we can
use that parsed report to test on it in the diagnose tests.
I've added separate specs for report structure and values. I didn't want
to mix them in the output specs even though they test the same values,
but I don't want to spec to fail if only the output or the report is
wrong.
I've added a new `expect_report_for` helper to test the report itself,
but this is not done yet, as it doesn't …

Submit diagnose reports to spec server

---

ruby/Gemfile.lock
spec/diagnose_spec.rb
spec/support/diagnose_report_helper.rb
spec/support/runner.rb

I consider the Ruby gem leading in most of the data that the report
includes, so I've updated it to expect the Ruby gem's format.
The other integrations will need to match it. The only exception I know
is the `user` and `group` keys for path ownership, it's not easy to get
these in all languages, so they're only required for the Ruby gem.
The report stub we use didn't include some fields the integration
does write to the report file.

Update diagnose specs to match Ruby gem format

---

spec/diagnose_spec.rb
spec/support/runner.rb

When we would release a new version of the Elixir package and then test
against it, it would create a directory in the build release directory
for that package version. Over time multiple versions could be in this
build release directory, causing the report stub behavior in
`after_setup` to be confused which package version to stub it in. It
would pick the first version, assuming there was only one directory.
I didn't want to do something like find the latest version of the
package, because that's not necessarily the one someone is currently
testing against.
Remove any AppSignal version package from the build release directory to
make sure it's always a clean state and it can't get confused about
which package version to write the report stubs to.
To standardize the install reports a bit …

Elixir diagnose specs updates

---

spec/diagnose_spec.rb

The request should contain the base information of the push_api_key and
some other app details we can use to link the report.
Closes #24

Add test for query params in report transmission

---

bin/test
elixir/config/config.exs
ruby/config/appsignal.yml
spec/diagnose_spec.rb
spec/support/diagnose_report_helper.rb
spec/support/server.rb

This PR is part of https://github.com/appsignal/appsignal-nodejs/issues/473.
This commit modifies the `bin/test` script so that extra arguments given to it are passed through to the `bundle exec rspec` invocation.
To separate the test for the `options` section of the config from the one for the `sources` section of the config, the `section` method in the `DiagnoseReport` is modified so that it takes a series of keys to pass to `Hash#dig` on the report, instead of a key to pass to `Hash#fetch`.
The implementation-pending assertions on the sources are moved to a separate test.
This commit implements the checks for the `sources` sub-section of the report for Ruby and Elixir. The Node.js implementation is still pending.
In order to test the behaviour when configuration variables are set in …

Test the report's "sources" sub-section

---

spec/diagnose_spec.rb

In PR #30, a test that checks that the name is sent as empty in the diagnose request params was added, while in PR #34, a config file that makes the name not empty was added for the Ruby and Elixir test projects.
This commit aligns the expectations in #30 with the changes in #34 by expecting the name to be set in Ruby and Elixir.

Expect params' `name` to be non-empty

---

spec/diagnose_spec.rb
spec/support/runner.rb

Closes #14 
The line was ignored previously but we have a flexible enough system now
to test this extra line for the Ruby gem.
Test if the dependencies and flags fields are printed in the diagnose
report. They were ignored before, but we can start testing them now.

Test previously ignored lines

---

spec/diagnose_spec.rb

See appsignal/appsignal-nodejs#484 for the implementation.
This commit adds checks for the sources section of the diagnose report for the Node.js integration.
This commit adds expectations for the Node.js report output to contain information about which sources provide which configuration values.

Add Node.js sources to the diagnose report

---

spec/diagnose_spec.rb
spec/support/runner.rb

This commit ensures that the `environment` configuration value is always set to `development` for all integrations. For the Node integration, it sets `NODE_ENV` instead of setting `APPSIGNAL_APP_ENV`.
To do so, the way environment variables are handled in the `Runner` and its subclasses is modified, with a new `run_env` function that subclasses can implement. `run_command` is also modified so that it takes the command-line arguments as an argument.
In order to continue testing the behaviour for the Node diagnose output when multiple configuration sources have values for the same configuration key, and in concordance with the behaviour of the other integrations, the `enable_minutely_probes` key is set to `false`, overriding its default value.
This commit removes `log_file_path` from the …

Fix Node.js sources environment and remove `log_path_file`

---

ruby/config/appsignal.yml

In #38, the default environment for the diagnose test projects was changed to be `development` instead of `test`, but the config file for the Ruby project was not changed accordingly; this commit fixes that.

Set config for development env

---

spec/diagnose_spec.rb
spec/spec_helper.rb
spec/support/server.rb

Add an extra endpoint to the MockServer to test the Push API key
validation.
I renamed the DiagnoseServer to MockServer to allow it to be used for
more tests.

Test Push API key validation

---

spec/diagnose_spec.rb

`valid` is no longer a config option for the Elixir library. Assertions
have been removed from the console and JSON reports.

Remove valid opt asserts for Elixir

---

ruby/Gemfile.lock
spec/diagnose_spec.rb
spec/support/server.rb

There's a new scenario that tests when the diagnose report fails to get
submitted to AppSignal.
Now, when mocking the diagnose request, we must add the expected
response code explicitly.
Closes #32

Add scenario for report submission failure

---

spec/diagnose_spec.rb

Update the spec to match the new config option name.
[skip review] because it's a small rename that's addressed in more detail in https://github.com/appsignal/appsignal-nodejs/pull/507.

The Node.js apiKey option is renamed to pushApiKey

---

spec/diagnose_spec.rb

The Node.js integration now has a system source. It's empty by default
unlike the other integrations, because it doesn't listen to the
`APPSIGNAL_PUSH_API_KEY` yet to set the active config option to `true`.
It's only there for the `log` option to "stdout" on Heroku dynos.
[skip review] because it's only another source addition, similar to what other integrations already have. The real review is in https://github.com/appsignal/appsignal-nodejs/pull/509

Add system source to Node.js config sources

---

spec/diagnose_spec.rb

requestHeaders key and functionality is now available for Node.js This
commit updates the matchers to check if defaults are set up.

Add requestHeaders config option to Node.js

---

spec/diagnose_spec.rb

It's automatically detected, but not set by default.
As per https://github.com/appsignal/appsignal-nodejs/pull/513
Part of https://github.com/appsignal/appsignal-nodejs/pull/525
[skip review]

Remove default logPath option for Node.js

---

spec/diagnose_spec.rb

Test if the `send_environment_metadata` config option is printed in the
Elixir and Node.js integrations now that they print it.

Add env metadata config option to Node.js & Elixir

---

spec/diagnose_spec.rb

In order to remove differences between the integrations behaviour, Ruby
config opts list is now printed alphabetically.

Order Ruby config opts alphabetically

---

spec/diagnose_spec.rb

This reverts commit a6f82cc61025a53ccd2d00ca1ef2a1cf3478a00f, reversing
changes made to 1e35baf3a08e1cc064314e25b9b8e29bae1f038c.
The log_level being set by default, makes sure that that the debug and
transaction_debug_mode options no longer function, which is not what we
want.

Revert log_level default config option

---

spec/diagnose_spec.rb

Elixir had some non-sense headers inherited from the Ruby integration
that were exclusive to `Rack`.
Updated the matchers to comply with the new list that only includes
headers that make sense.
Implemented in: https://github.com/appsignal/appsignal-elixir/pull/741

Update default headers for Elixir

---

spec/diagnose_spec.rb

Node.js now accepts the `sendParams` config option. This change updates
the integration matcher.

Add sendParams option for Node.js

---

spec/diagnose_spec.rb

The `sendSessionData` is now available in the Node.js integration. This
commit adds it to the test.

Add sendSessionData to Node.js tests

---

nodejs/package.json
spec/support/runner.rb

As the extension package is now merged inside the Node.js core package,
there's no need to install it anymore.

Remove extension package from Node.js deps

---

spec/diagnose_spec.rb

We've deprecated skip_session_data in favor of send_session_data in the
Ruby gem.
Part of https://github.com/appsignal/appsignal-ruby/issues/802

Use send_session_data in Ruby gem tests

---

spec/diagnose_spec.rb

This matches the changes introduced in [appsignal-nodejs#548][pr], where the `active` config option is added to the default values, and the configuration object is not invoked with `active` set to `true` as an initial value in the diagnose.
[pr]: https://github.com/appsignal/appsignal-nodejs/pull/548

Expect active to be false on Node.js

---

spec/support/runner.rb

In PR https://github.com/appsignal/appsignal-nodejs/pull/553 the `install.report` path is updated to be stored in the
`nodejs/ext` directory now that the package persists on the file system
after an installation failure.

Store Node.js install report in the ext dir

---

spec/diagnose_spec.rb

The `send_session_data` is the new option to be used after the
deprecation of `skip_session_data`. This commit updates the Elixir tests
to match with the new option.

Add send_session_data to Elixir

---

spec/diagnose_spec.rb

Add override config source to Elixir specs for the `skip_session_data`
and `send_session_data` config options.
This allows to see better when certain config options are set in the
configuration process. This config source is leading.
Part of https://github.com/appsignal/appsignal-elixir/issues/752

Add Elixir override config source

---

spec/diagnose_spec.rb

I'm developing on an ARM machine and the test fail because it expects
x86 architecture. Add the ARM architecture as well so it will run
locally.
For the Ruby gem we now track `send_session_data` in the `override`
config source. The system source is too early in the config load order
and it was previously set much later, which meant it could result in an
inaccurate diagnose report.
Part of https://github.com/appsignal/appsignal-ruby/issues/811

Ruby move send_session_data to the override source

---

spec/support/runner.rb

It's no longer a mono repo. Remove the package specific location.
Used by https://github.com/appsignal/appsignal-nodejs/pull/689
[skip review]

Update path for Node.js single repo package

---

spec/diagnose_spec.rb

Remove `debug` and `transactionDebugMode` config options. They have both been replaced with the `logLevel` config option.
Part of https://github.com/appsignal/appsignal-nodejs/issues/738

Remove unused debug config options

---

spec/diagnose_spec.rb

We've released a beta version and the diagnose tests failed on that because it didn't expect the prerelease suffix. I've updated the version matcher to account for that.
[skip review]

Fix Node.js version matcher

---

spec/diagnose_spec.rb

This helps us with debugging what exact version of Linux an app is running on, for example.
[skip review]
Required for https://github.com/appsignal/appsignal-ruby/pull/901

Track OS distro in diagnose report

---

spec/diagnose_spec.rb

It would print things like `False`, `not started`, and `not writable` for tests that weren't present. This doesn't mean they are not writable, only that we couldn't test it. Most likely because the config wasn't loaded and it didn't know what paths to check.
Fix the format to match the other integrations and print a dash instead.
Part of https://github.com/appsignal/appsignal-python/pull/108

Fix formatting for Python agent tests

---

python/__appsignal__.py
spec/diagnose_spec.rb
spec/support/diagnose_report_helper.rb
spec/support/runner.rb
spec/support/runner_helper.rb

This PR includes the necessary changes to run the diagnose integration tests in the Python integration.
Python's diagnose command PR: https://github.com/appsignal/appsignal-python/pull/89

Add Python diagnose scenarios

---

spec/diagnose_spec.rb

Part of https://github.com/appsignal/appsignal-python/issues/27
Required for https://github.com/appsignal/appsignal-python/pull/118

Add Python opentelemetry_port config option

---

spec/diagnose_spec.rb

The Python diagnose CLI didn't print all the path details other integrations do. This change now asserts that it does.
Not sure why on Node.js the "Log directory" doesn't output the same details, but that's out of the scope of this change for Python. Otherwise I would have removed that if-statement around the log directory's assertions.
Related to https://github.com/appsignal/appsignal-python/pull/159

Assert more details about paths in Python

---

spec/diagnose_spec.rb

Test if these two new library fields are present in the report.
Related to https://github.com/appsignal/appsignal-python/pull/170

Add package architecture and platform for Python

---

spec/diagnose_spec.rb

Check if this extra path is present in the report to help debug path related issues.
Part of https://github.com/appsignal/appsignal-python/pull/171
Based on #99

Assert the Python package's package path

---

spec/diagnose_spec.rb

For the Python package we need a way to communicate if the app host is a container or not. The agent diagnose report is used for this, update the matchers to match.
This field will be present for all integrations, not just Python.
Part of https://github.com/appsignal/appsignal-python/issues/172

Add running_in_container to agent diagnose report

---

spec/diagnose_spec.rb

The Node.js integration was the only integration that didn't list these path details, but now it does.
Needed for https://github.com/appsignal/appsignal-nodejs/pull/958

Assert all path details for Node.js integration

---

spec/diagnose_spec.rb

The path for the `mkmf.log` file has changed. It's no longer expected to be in a `ext/` sub dir. It's in a completely different dir. This is better tested in the Ruby gem itself.
Related PR: https://github.com/appsignal/appsignal-ruby/pull/1022
Related issue: https://github.com/appsignal/appsignal-ruby/issues/1018

Update Ruby gem Makefile log path key assertion

---

spec/diagnose_spec.rb
spec/support/runner.rb

It now uses a numbered version so no need for its own matcher. I kept the constant name different so it communicates more clearly what it's matching.
[skip review]

Update agent version matcher

---

spec/diagnose_spec.rb

This option defines the port of the agent's HTTP OTel server.

Add OpenTelemetry port to Node

---

spec/diagnose_spec.rb

REQUEST_URI is no longer a default header this commit changes it to REQUEST_PATH
Part of: https://github.com/appsignal/appsignal-ruby/issues/1038

Update Ruby headers default values

---

bin/test-all
spec/support/runner.rb

Context: https://github.com/appsignal/appsignal-python/pull/196
A warning is raised about not being able to find the configuration
file. Ignore it.
On the script that tests against all languages, add support for
Python alongside the other languages.

Read config improvements

---

spec/diagnose_spec.rb
spec/support/runner.rb

In a recent version of hatch, they made sure the working directory stays the same for `hatch run`. It will now be the directory in which the `hatch run` was run, not be the project directory of the package you're running.
Update the paths to match the working directory of the diagnose tests submodule.
Now that it uses the correct working directory, it also loads the `__appsignal__.py` config file correctly, so update the initial config source content. Remove the ignored line that hid this issue.
[skip review]

Fix Python diagnose working dir and initial config

---

.rubocop.yml
spec/diagnose_spec.rb

Last change I found it difficult to follow when the modified hash and arrays in this commit ended. There were a bunch of `}` on one line.
Enable rules to enforce the first key/value in a hash or array always start on a new line in multi line definitions.
[skip reviewo

Enable First*ElementLineBreak RuboCop rules

---

.rubocop.yml
ruby/Gemfile.lock
spec/diagnose_spec.rb
spec/support/runner.rb

I got this error when performing this spec. Match a String instead so the error goes away.
> RegexpError: empty char-class
It would fail on this line of output being present, so ignore it.
Not sure how it worked before, but explicitly install the runner's gems from the Gemfile, which includes the Ruby gem it's testing. I ran into errors of the gem not being found.
Fix issues with the wrong bundle of gems being used as context for the runner. This failed to find the Ruby gem as it was using this project's test suite Gemfile instead.
Wrap commands with `Bundler.with_unbundled_env` so it removes any Bundler context from the environment. It also clears some other env vars, so explicitly set them again in the base `run_env` method.

Fix runner for Ruby setup on GitHub Actions

---

ruby/Gemfile.lock
spec/diagnose_spec.rb

Remove these options in preparation of the Ruby gem 4 release.
[skip review]

Remove deprecate Ruby gem options

---

spec/diagnose_spec.rb

This behavior was removed from Ruby gem 4.
Part of https://github.com/appsignal/appsignal-ruby/pull/1224
[skip review]

Remove Ruby config modifiers
